# Generated by Django 4.0.1 on 2022-03-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('code', models.CharField(max_length=30, verbose_name='Код подтверждения')),
                ('is_active', models.BooleanField(default=False, verbose_name='Является ли действительным')),
                ('expire_at', models.DateTimeField(verbose_name='Действует до')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
            ],
            options={
                'verbose_name': 'Код подтверждение email',
                'verbose_name_plural': 'Коды подтверждение email',
                'db_table': 'verification_code',
            },
        ),
    ]
